### ISSUE TITLE
State_level data?

### ISSUE THREAD

**Issue by kmussar** [JieYingWu/COVID-19_US_County-level_Summaries#145]
Hi, your dataset is great! I'm not able to find the `states_only.csv ` however. Was this taken down? 

Thanks!
Kristin

**Comment by JieYingWu** [comment]
Thanks! Yeah, we stopped publishing the state data separately and instead put everything counties.csv. You can filter for states only by selecting the counties with FIPS ending in 000. 

Hope that helps!
Jie Ying
