### ISSUE TITLE
public schools rollback

### ISSUE THREAD

**Issue by gunnarsundberg** [JieYingWu/COVID-19_US_County-level_Summaries#162]
Are there any plans to add `public school rollback` data in the `data/interventions.csv` file? The rollback could be the date that schools reopen in-person classes. I know that there are some school districts that are already meeting in person. It would be very useful to be able to study the effects of reopening schools. Thanks for your consideration!

**Comment by JieYingWu** [comment]
Unfortunately, there is currently no plans to add public schools as we did not find a central repository of that information, even on the state level. We try to start with at least that, and then look into specific counties on a case by case basis. If you know of any source that could jump start a collection effort, please let us know and we can pull that in.
