### ISSUE TITLE
Metadata for interventions.csv?

### ISSUE THREAD

**Issue by mymil** [JieYingWu/COVID-19_US_County-level_Summaries#163]
Re https://github.com/JieYingWu/COVID-19_US_County-level_Summaries/blob/master/data/interventions.csv

**Problem**
For many interventions for many states, that dates are identical for all counties. This suggests that (a) interventions were imposed at the state, rather than the county, level and/or (b) county-level data were not available or collected. Treating data that is actually state-level as county-level downwardly biases standard errors and gives a false perception of estimate precision.

**Suggested resolution**
It would be useful to include a column of metadata (or a column of metadata for every intervention, if necessary) indicating the unit of observation to which a given intervention date applies: county or state.

**Comment by JieYingWu** [comment]
Hello! Thank you for pointing this out - we agree that we should have made a note on this when initially collecting the data but as the interventions were collected manually, it would be more effort than we can expand now to reconstruct. One work around may be to compare the county intervention to the one reported for the state row and see if it matches - while this does not definitely tell you if it's state level if they match, it would tell you if it's county-level if the intervention is implemented on a different date from the state.
