### ISSUE TITLE
Showing rollback on rollbacks in interventions.csv?

### ISSUE THREAD

**Issue by bpblakely** [JieYingWu/COVID-19_US_County-level_Summaries#164]
As you may know, some states are rolling back their rollbacks. In other words, lifting a restriction only to start enforcing it again a month later. Do you have any plans to support a rollback on a rollback for policies in interventions.csv? Thanks!

**Comment by JieYingWu** [comment]
We do not currently have plans to do this. If you know sources that have started to this effort, we are happy to consider incorporating it into our dataset.
