### ISSUE TITLE
Raw data source for `interventions.csv`?

### ISSUE THREAD

**Issue by huisaddison** [JieYingWu/COVID-19_US_County-level_Summaries#45]
Hi there, thanks so much for your hard work compiling this valuable data.

I can't seem to find the data source for `data/interventions.csv`.  It seems
to me that it is a processed version of `raw_data/national/public_implementations_fips.csv`,
but I cannot find documentation for the source of that data.

Thanks for your help!

**Comment by benjamindkilleen** [comment]
Hi! Thank you for your interest in our dataset.

The sources for our interventions data are widespread. They can now be found in the data readme: https://github.com/JieYingWu/COVID-19_US_County-level_Summaries/tree/master/data
